export const SET_UNIVERSITIES = "SET_UNIVERSITIES";
export const SET_SELECTED_UNIVERSITY = "SET_SELECTED_UNIVERSITY";
export const SET_SELECTED_CITY = "SET_SELECTED_CITY";
export const SET_STATUS = "SET_STATUS";
export const SET_PAROL = "SET_PAROL";
export const SET_EMAIL = "SET_EMAIL";
export const SET_COMPLETED = "SET_COMPLETED";
